#!/bin/bash

######### Save secret files ########
git secret hide


######### Static analyzing ########
echo "Running static analyzer"
./gradlew --quiet --daemon detekt
if [ $? -ne 0 ]; then exit 1; fi


######### Code formatting ########
CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt/ { print $2}')"
if [ -z "$CHANGED_FILES" ]; then exit 0; fi

echo "Running ktlint over these files:"
echo "$CHANGED_FILES"

./gradlew --quiet --daemon ktlintFormat -PinternalKtlintGitFilter="$CHANGED_FILES"
echo "$CHANGED_FILES" | while read -r file; do
    if [ -f $file ]; then
        git add $file
    fi
done
